title: Server Migration Documentation
description: Things to keep in mind while migrating server!!
theme: just-the-docs

url: https://exceptionSPG.github.io/server-migration

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
